In [1]:
import numpy as np
import copy

from misc import generate_random_transport_problem

# Example usage
num_sources = 5
num_destinations = 6
min_cost = 1
max_cost = 10
min_supply = 10
max_supply = 40
min_demand = 5
max_demand = 30

cost_matrix, supply, demand = generate_random_transport_problem(num_sources, num_destinations, min_cost, max_cost, min_supply, max_supply, min_demand, max_demand)

print("Generated Transportation Problem:")
print("Cost Matrix:")
print(cost_matrix)
print("Supply:", supply)
print("Demand:", demand)

Generated Transportation Problem:
Cost Matrix:
[[ 7  2  7  6  4 10]
 [ 6  3  3  3  1  4]
 [ 4  7  8  5  2  1]
 [ 6  1  1  6 10  9]
 [ 2  9  4 10 10 10]]
Supply: [ 8 36 32 13 21]
Demand: [29  9 16 17 21 18]


In [2]:
# # Define the cost matrix
# cost_matrix = np.array([[10, 2, 20, 11], 
#                         [12, 7, 9, 20],
#                         [4, 14, 16, 18]])

# # Define the supply and demand constraints
# supply = np.array([15, 25, 10])
# demand = np.array([5, 15, 15, 15])

In [3]:
from simplex import simplex_method
from northwest import northwest_corner_method
from least import least_cost_cell_method
from vogel import vogels_approximation_method
from tp_potential import Data
from tp_potential import solve as potential_method

In [4]:
from misc import test_time_mem

In [5]:
res = test_time_mem(simplex_method, cost_matrix, supply, demand)
transportation_matrix, cost = res["transportation_matrix"], res["cost"]
print(transportation_matrix)
print("Simplex method cost: ", cost)

c:\Users\Nick\Documents\Programming\Python\transport-problem\simplex.py:34: OptimizeWarning: A_eq does not appear to be of full row rank. To improve performance, check the problem formulation for redundant equality constraints.
  res = linprog(c, A_eq=A_eq, b_eq=b_eq, method='simplex')


Filename: c:\Users\Nick\Documents\Programming\Python\transport-problem\simplex.py

Line #    Mem usage    Increment  Occurrences   Line Contents
     8     99.7 MiB     99.7 MiB           1   def simplex_method(cost_matrix, supply, demand):
     9                                             # Create the coefficient matrix for the constraints
    10     99.7 MiB      0.0 MiB           1       num_sources = len(supply)
    11     99.7 MiB      0.0 MiB           1       num_destinations = len(demand)
    12     99.7 MiB      0.0 MiB           1       num_variables = num_sources * num_destinations
    13                                         
    14     99.7 MiB      0.0 MiB           1       A_eq = np.zeros((num_sources + num_destinations, num_variables))
    15                                         
    16                                             # Supply constraints
    17     99.7 MiB      0.0 MiB           6       for i in range(num_sources):
    18     99.7 MiB      0.0 MiB   

In [6]:
res = test_time_mem(northwest_corner_method, cost_matrix, supply, demand)
transportation_matrix, cost = res["transportation_matrix"], res["cost"]
print(transportation_matrix)
print("Nowrthwest method cost: ", cost)

Filename: c:\Users\Nick\Documents\Programming\Python\transport-problem\northwest.py

Line #    Mem usage    Increment  Occurrences   Line Contents
     6    100.8 MiB    100.8 MiB           1   def northwest_corner_method(cost_matrix, supply, demand):
     7    100.8 MiB      0.0 MiB           1       num_sources = len(supply)
     8    100.8 MiB      0.0 MiB           1       num_destinations = len(demand)
     9                                             
    10                                             # Initialize the transportation matrix
    11    100.8 MiB      0.0 MiB           1       transport_matrix = np.zeros((num_sources, num_destinations))
    12                                             
    13                                             # Iterate over the sources and destinations
    14    100.8 MiB      0.0 MiB           1       i = 0
    15    100.8 MiB      0.0 MiB           1       j = 0
    16    100.8 MiB      0.0 MiB          11       while i < num_sources a

In [7]:
res = test_time_mem(least_cost_cell_method, cost_matrix, supply, demand)
transportation_matrix, cost = res["transportation_matrix"], res["cost"]
print(transportation_matrix)
print("Least Cost Cell method cost: ", cost)

Filename: c:\Users\Nick\Documents\Programming\Python\transport-problem\least.py

Line #    Mem usage    Increment  Occurrences   Line Contents
     6    100.8 MiB    100.8 MiB           1   def least_cost_cell_method(cost_matrix, supply, demand):
     7    100.8 MiB      0.0 MiB           1       num_sources = len(supply)
     8    100.8 MiB      0.0 MiB           1       num_destinations = len(demand)
     9                                             
    10                                             # Initialize the transportation matrix
    11    100.8 MiB      0.0 MiB           1       transport_matrix = np.zeros((num_sources, num_destinations))
    12                                             
    13                                             # Create a copy of the cost matrix for tracking remaining cells
    14    100.8 MiB      0.0 MiB           1       remaining_matrix = cost_matrix.copy()
    15                                             
    16                          

In [8]:
res = test_time_mem(vogels_approximation_method, cost_matrix, supply, demand)
transportation_matrix, cost = res["transportation_matrix"], res["cost"]
print(transportation_matrix)
print("Vogel's Approximation method cost: ", cost)

Filename: c:\Users\Nick\Documents\Programming\Python\transport-problem\vogel.py

Line #    Mem usage    Increment  Occurrences   Line Contents
     8    100.8 MiB    100.8 MiB           1   @timeout(1)
     9                                         @profile
    10                                         def vogels_approximation_method(cost_matrix, supply, demand):
    11    100.8 MiB      0.0 MiB           1       num_sources = len(supply)
    12    100.8 MiB      0.0 MiB           1       num_destinations = len(demand)
    13                                             
    14                                             # Initialize the transportation matrix
    15    100.8 MiB      0.0 MiB           1       transport_matrix = np.zeros((num_sources, num_destinations))
    16                                             
    17                                             # Create a copy of the cost matrix for tracking remaining cells
    18    100.8 MiB      0.0 MiB           1       re

In [9]:
data = Data(
    supply.copy(),
    demand.copy(),
    copy.deepcopy(cost_matrix),
)

res = test_time_mem(potential_method, cost_matrix, potential=True, data=data)
transportation_matrix, cost = res["transportation_matrix"], res["cost"]
print(transportation_matrix)
print("Potential method cost: ", cost)

Filename: c:\Users\Nick\Documents\Programming\Python\transport-problem\tp_potential\solver.py

Line #    Mem usage    Increment  Occurrences   Line Contents
    18    100.9 MiB    100.9 MiB           1   @timeout(1)
    19                                         @profile
    20                                         def solve(data: Data, use_nw_corner_method: bool = False):
    21    100.9 MiB      0.0 MiB           1       try:
    22    100.9 MiB      0.0 MiB           1           if use_nw_corner_method:
    23                                                     x = get_start_plan_by_north_west_corner_method(data)
    24                                                 else:
    25    100.9 MiB      0.0 MiB           1               x = get_start_plan_by_min_element_method(data)
    26                                                 # x = data.c
    27                                                 # print(x)
    28                                         
    29    100.9 MiB      